/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __CLUSTERLABELING_ALL_TYPES_H__
#define __CLUSTERLABELING_ALL_TYPES_H__

#include <clusterLabeling/types/type_definitions.h>


#endif /* __CLUSTERLABELING_ALL_TYPES_H__ */
