/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __CLUSTERLABELING_TYPE_DEFINITIONS_H__
#define __CLUSTERLABELING_TYPE_DEFINITIONS_H__


#endif /* __CLUSTERLABELING_TYPE_DEFINITIONS_H__ */
