/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __ACTIONSERVER_ALL_TYPES_H__
#define __ACTIONSERVER_ALL_TYPES_H__

#include <actionserver/types/type_definitions.h>


#endif /* __ACTIONSERVER_ALL_TYPES_H__ */
