/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __ACTIONSERVER_TYPE_DEFINITIONS_H__
#define __ACTIONSERVER_TYPE_DEFINITIONS_H__


#endif /* __ACTIONSERVER_TYPE_DEFINITIONS_H__ */
