ae:
  name: demo
fixedflow:
  - CollectionReader
  - ImagePreprocessor
  - PointCloudFilter
  - NormalEstimator
  - PlaneAnnotator
  - PointCloudClusterExtractor
  - ClusterMerger
  - ClusterColorHistogramCalculator
  - Cluster3DGeometryAnnotator
  - TFBroadcaster 
 
CollectionReader:
  camera_config_files: ['config_hsrb.ini']

PlaneAnnotator:
  horizontal: false
  vertical: true
  min_plane_inliers: 5000

PointCloudClusterExtractor:

ClusterColorHistogramCalculator:
  semantic_label: true
