/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __SUTURO_PERCEPTION_ALL_TYPES_H__
#define __SUTURO_PERCEPTION_ALL_TYPES_H__

#include <suturo_perception/types/type_definitions.h>


#endif /* __SUTURO_PERCEPTION_ALL_TYPES_H__ */
