/*
 * This file was generated by generate_typesystem.py.
 * Filename:    property_types
 * Name:        property
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __PROPERTY_TYPES_H__
#define __PROPERTY_TYPES_H__

#include <robosherlock/feature_structure_proxy.h>
#include <suturo_perception/types/type_definitions.h>
#include <robosherlock/types/core_types.h>
#include <robosherlock/types/tf_types.h>

namespace suturo_perception
{

/*
 * No description given
 */
class BoundingBox : public rs::Annotation
{
private:
  void initFields()
  {
    width.init(this, "width");
    height.init(this, "height");
    depth.init(this, "depth");
  }
public:
  // No description given
  rs::FeatureStructureEntry<float> width;
  // No description given
  rs::FeatureStructureEntry<float> height;
  // No description given
  rs::FeatureStructureEntry<float> depth;

  BoundingBox(const BoundingBox &other) :
      rs::Annotation(other)
  {
    initFields();
  }

  BoundingBox(uima::FeatureStructure fs) :
      rs::Annotation(fs)
  {
    initFields();
  }
};

/*
 * Annotation of a semantic region
 */
class Region : public rs::Annotation
{
private:
  void initFields()
  {
    transform.init(this, "transform");
    name.init(this, "name");
    type.init(this, "type");
    width.init(this, "width");
    height.init(this, "height");
    depth.init(this, "depth");
  }
public:
  // Region transform
  rs::ComplexFeatureStructureEntry<rs::StampedTransform> transform;
  // Region name
  rs::FeatureStructureEntry<std::string> name;
  // Region type
  rs::FeatureStructureEntry<std::string> type;
  // No description given
  rs::FeatureStructureEntry<float> width;
  // No description given
  rs::FeatureStructureEntry<float> height;
  // No description given
  rs::FeatureStructureEntry<float> depth;

  Region(const Region &other) :
      rs::Annotation(other)
  {
    initFields();
  }

  Region(uima::FeatureStructure fs) :
      rs::Annotation(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(suturo_perception::BoundingBox, SUTURO_PERCEPTION_PROPERTY_BOUNDINGBOX)
TYPE_TRAIT(suturo_perception::Region, SUTURO_PERCEPTION_PROPERTY_REGION)

#endif /* __PROPERTY_TYPES_H__ */
