/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __SUTURO_PERCEPTION_TYPE_DEFINITIONS_H__
#define __SUTURO_PERCEPTION_TYPE_DEFINITIONS_H__


#endif /* __SUTURO_PERCEPTION_TYPE_DEFINITIONS_H__ */
