/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_PERCEPTION_ALL_TYPES_H__
#define __RS_PERCEPTION_ALL_TYPES_H__

#include <rs_perception/types/type_definitions.h>


#endif /* __RS_PERCEPTION_ALL_TYPES_H__ */
